name: Create Release Tag

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: Tagging dry run
        default: true

  pull_request:
    types: [closed]
    branches: [main]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  release:
    name: Increment Version
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - id: check_inputs
        env:
          INPUT_DRY_RUN: ${{ github.event.inputs.dry_run }}
        run: |
          echo "dry_run=${INPUT_DRY_RUN:-"false"}" >> "$GITHUB_OUTPUT"

      - name: Generate Next Version
        uses: reecetech/version-increment@71036b212bbdc100b48aae069870f10953433346 # 2023.10.2
        id: version-increment
        with:
          scheme: calver
          use_api: true

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        if: steps.check_inputs.outputs.dry_run == false
        run: >-
          gh release create
          '${{ steps.version-increment.outputs.version }}'
          --repo '${{ github.repository }}'
          --latest
          --generate-notes
