name: Publish autopkg-wrapper to PyPI/TestPyPI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Build
        run: poetry build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  deploy_test:
    name: Deploy distribution to TestPyPI 🚀
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: testpypi
      url: https://test.pypi.org/p/autopkg-wrapper
    permissions:
        id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1

  # deploy_prod:
  #   name: Deploy distribution to PyPI 🚀
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/autopkg-wrapper
  #   permissions:
  #       id-token: write

  #   steps:
  #     - name: Download all the dists
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: python-package-distributions
  #         path: dist/
  #     - name: publish
  #       uses: pypa/gh-action-pypi-publish@release/v1
